all:
  children:
    server:
      hosts:
        54.165.86.20:
          router_private_ip: "172.31.10.142"
          server_private_ip: "172.31.13.147"
          ansible_ssh_private_key_file: "secret_vars/key_pair_1_sysadmin"
          ansible_user: "ubuntu"
          ansible_python_interpreter: "/usr/bin/python3"
    router:
      hosts:
        3.87.116.47:
          router_private_ip: "172.31.10.142"
          server_private_ip: "172.31.13.147"
          hostname: "RTR"
          ansible_ssh_private_key_file: "secret_vars/key_pair_1_sysadmin"
          ansible_user: "vyos"
          ansible_network_os: vyos.vyos.vyos
          ansible_connection: ansible.netcommon.network_cli

