all:
  children:
    server:
      hosts:
        54.208.231.236:
          router_private_ip: "172.31.15.62"
          server_private_ip: "172.31.9.101"
          ansible_ssh_private_key_file: "secret_vars/key_pair_1_sysadmin"
          ansible_user: "ubuntu"
          ansible_python_interpreter: "/usr/bin/python3"
    router:
      hosts:
        34.224.23.46:
          router_private_ip: "172.31.15.62"
          server_private_ip: "172.31.9.101"
          hostname: "RTR"
          ansible_ssh_private_key_file: "secret_vars/key_pair_1_sysadmin"
          ansible_user: "vyos"
          ansible_network_os: vyos.vyos.vyos
          ansible_connection: ansible.netcommon.network_cli

