all:
  children:
    server:
      hosts:
        54.196.14.34:
          router_private_ip: "172.31.7.56"
          server_private_ip: "172.31.13.241"
          ansible_ssh_private_key_file: "secret_vars/key_pair_1_sysadmin"
          ansible_user: "ubuntu"
          ansible_python_interpreter: "/usr/bin/python3"
    router:
      hosts:
        34.236.144.94:
          router_private_ip: "172.31.7.56"
          server_private_ip: "172.31.13.241"
          hostname: "RTR"
          ansible_ssh_private_key_file: "secret_vars/key_pair_1_sysadmin"
          ansible_user: "vyos"
          ansible_network_os: vyos.vyos.vyos
          ansible_connection: ansible.netcommon.network_cli

