# ---
# pod_up.yml
#
# Ansible playbook que levanta un POD en AWS para realizar la prueba de ingreso
# de Operaciones. El mismo levanta 2 servidores:
#   - `serverNum1`: Servidor con Docker instalado y múltiples servicios.
#   - `router`: Router CISCO CSR1000
# ---

- name: Levantar maquinas virtuales en AWS
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - include_tasks: ./tasks/aws_amis_up.yml
  vars_files:
    - ./vars/pod.yml

- name: Configuración de servidor
  hosts: server
  gather_facts: yes
  roles:
    - geerlingguy.docker
  tasks:
    - include_tasks: ./tasks/aws_server_configure.yml
  vars_files:
    - ./vars/pod.yml

- name: Configuración del router
  hosts: router
  gather_facts: no
  tasks:
    - include_tasks: ./tasks/aws_router_configure.yml
  vars_files:
    - ./vars/pod.yml
