# ---
# aws_server_configure.yml
# ---

- name: configure the remote device
  vyos.vyos.vyos_config:
    lines:
    - set system host-name {{ inventory_hostname }}
    - delete service dhcp-server
    - delete service ssh disable-password-authentication
  when: hostname is defined

- name: create a new user
  vyos.vyos.vyos_user:
    name: admin
    configured_password: admin
    level: admin
    state: present